---
title: "Aircraft Operator Groups"
format: html
---

The aircraft operator groupings used in EUROCONTROL are described in the [EUROCONTROL Airline groups lookup](https://www.eurocontrol.int/directory/airline-groups-lookup) page.

The EUROCONTROL table containing the aircraft operator group information (LDW_ACC.AO_GROUPS_ASSOCIATION) is managed by the Data Coordination Group. The table is however quite messy so for the AIU use, the following views have been created:

-   V_COVID_DIM_AO - Contains all current airline codes without duplicated lines indicating the groups 1 and 2 they belong to. In particular, the field AO_GRP_LEVEL indicates whether the aircraft operator belongs to a group 1 (GROUP1) or are individual aircraft operators (GROUP1_OTHER).

-   V_COVID_REL_AO_GROUP2 - Contains only the airline codes that belong to a group 2 and the details of the group 2.

-   V_COVID_REL_AO_ASSOC - Contains only the airline codes that belong to an association and the details of the association.
