---
title: "Country Definitions"
format: html
tbl-cap-location: bottom
page-layout: full
---

## PRU

The definition of a country in this section is mostly based on the ISO denomination and defined by the airports included in it. It should not be confused with other entities like FIRs, ANSPs, charging zones or traffic zones.

The EUROCONTROL Airport Reference Table (`DWH_PL.DIM_EC_ICAO_AIRPORT`, managed by the Data Coordination Group via [Collibra](https://eurocontrol.collibra.com/asset/a2dd76c2-29ba-4a72-8790-cdc4974935fc)) maps every airport to the ISO 2-letter code of the region/country it belongs to. This mapping is done at the lowest possible level (i.e. if the region has an official ISO code, this is used and not the code of the sovereign country). This allows experts across the Agency to use the grouping that suits their needs.

The PRU airport table (`PRU_DEV.PRU_AIRPORT`) is a view on the EUROCONTROL Airport Reference Table containing airports that are currently 'active'. In order to allocate the airports as in the table below, you need join it with the table `PRU_COUNTRY_ISO` and use the field `AIU_ISO_COUNTRY_NAME` as your country. These are the default definitions to be used in AIU products, unless there are reasons to do otherwise.

The `PRU_COUNTRY_ISO` country table is in line with the official EUROCONTROL Country Reference Table `DWH_PL.DIM_EC_ISO_COUNTRY`, which is also managed by the Data Coordination Group via [Collibra](https://eurocontrol.collibra.com/dashboard?d=adc56b9a-6665-4f90-a56b-483733a88bc7)) and is in line with EUROCONTROL Legal Service's recommendations.

+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Country                | Airports included                                                                                                                                                                     | Additional notes                                                                                                                                                                                                         |
+========================+=======================================================================================================================================================================================+==========================================================================================================================================================================================================================+
| Albania                | All airports with ICAO code starting by 'LA'. Same set as airports allocated to ISO code 'AL'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Armenia                | All airports with ICAO code starting by 'UD'. Same set as airports allocated to ISO code 'AR'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Austria                | All airports with ICAO code starting by 'LO'. Same set as airports allocated to ISO code 'AT'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Belgium                | All airports with ICAO code starting by 'EB'. Same set as airports allocated to ISO code 'BE'.                                                                                        | Note that STATFOR considers the single traffic zone 'Belgium/Luxembourg'.                                                                                                                                                |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bosnia and Herzegovina | All airports with ICAO code starting by 'LQ'. Same set as airports allocated to ISO code 'BA'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bulgaria               | All airports with ICAO code starting by 'LB'. Same set as airports allocated to ISO code 'BG'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Croatia                | All airports with ICAO code starting by 'LD'. Same set as airports allocated to ISO code 'HR'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Cyprus                 | All airports with ICAO code starting by 'LC' except LCEN and LCRA?. Same set as airports allocated to ISO code 'CY'.                                                                  |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Czech Republic         | All airports with ICAO code starting by 'LK'. Same set as airports allocated to ISO code 'CZ'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Denmark                | All airports with ICAO code starting by 'EK'. This includes the airports in the Faroe Islands (EKVG) which are allocated to the ISO code 'FO' in the Airport Reference Table.         | This is a difference with respect to the Denmark STATFOR traffic zone which does not include the Faroe Islands as they are part of the oceanic Faroe Islands traffic zone.                                               |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Same set as airports allocated to ISO code 'DK+FO'.                                                                                                                                   |                                                                                                                                                                                                                          |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Greenland is not included.                                                                                                                                                            |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Estonia                | All airports with ICAO code starting by 'EE'. Same set as airports allocated to ISO code 'EE'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Finland                | All airports with ICAO code starting by 'EF'. Same set as airports allocated to ISO code 'FI'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| France                 | All airports with ICAO code starting by 'LF' except Saint-Pierre (LFVP) and Miquelon (LFVM).                                                                                          | This is a small difference with respect to the France STATFOR traffic zone, which also excludes Saint-Pierre and Miquelon but includes Monaco (LNMC) as it is too small to have its own traffic zone.                    |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Same set as airports allocated to ISO code 'FR'.                                                                                                                                      |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Georgia                | All airports with ICAO code starting by 'UG'. Same set as airports allocated to ISO code 'GE'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Germany                | All airports with ICAO code starting by 'ED' or 'ET'. Same set as airports allocated to ISO code 'DE'.                                                                                |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Greece                 | All airports with ICAO code starting by 'LG'. Same set as airports allocated to ISO code 'GR'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Hungary                | All airports with ICAO code starting by 'LH'. Same set as airports allocated to ISO code 'HU'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ireland                | All airports with ICAO code starting by 'EI'. Same set as airports allocated to ISO code 'IE'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Israel                 | All airports with ICAO code starting by 'LL'. Same set as airports allocated to ISO code 'IL'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Italy                  | All airports with ICAO code starting by 'LI'. Same set as airports allocated to ISO code 'IT'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Kosovo\*               | All airports with ICAO code starting by 'BK' plus airport 'LYPR'.                                                                                                                     | \* This designation is without prejudice to positions on status, and is in line with UNSCR 1244/99 and the ICJ opinion on the Kosovo declaration of independence.                                                        |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Two different ICAO codes exist in the NM systems to designate Pristina airport - BKPR and LYPR. The PRU joins both designators under a single entity.                                 |                                                                                                                                                                                                                          |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Same set as airports allocated to ISO code 'XK'.                                                                                                                                      |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Latvia                 | All airports with ICAO code starting by 'EV'. Same set as airports allocated to ISO code 'LV'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lithuania              | All airports with ICAO code starting by 'EY'. Same set as airports allocated to ISO code 'LT'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Luxembourg             | All airports with ICAO code starting by 'EL'. Same set as airports allocated to ISO code 'LU'.                                                                                        | Note that STATFOR considers the single traffic zone 'Belgium/Luxembourg'.                                                                                                                                                |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Malta                  | All airports with ICAO code starting by 'LM'. Same set as airports allocated to ISO code 'MT'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Moldova                | All airports with ICAO code starting by 'LU'. Same set as airports allocated to ISO code 'MD'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Montenegro             | All airports allocated to the [ISO code 'ME']{.underline} in the EUROCONTROL Airport Reference Table.                                                                                 | Note that STATFOR considers the single traffic zone 'Serbia/Montenegro'.                                                                                                                                                 |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Morocco                | All airports with ICAO code starting by 'GM'. Same set as airports allocated to ISO code 'MA'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Netherlands            | All airports with ICAO code starting by 'EH'. Same set as airports allocated to ISO code 'NL'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| North Macedonia        | All airports with ICAO code starting by 'LW'. Same set as airports allocated to ISO code 'MK'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Norway                 | All airports with ICAO code starting by 'EN'. This includes airports in Svalbard (ENGA) and Jan Mayen (ENJA) which are allocated to the ISO code 'SJ' in the Airport Reference Table. | This is a difference with respect to the Norway STATFOR traffic zone which does not include the Svalbard and Jan Mayen as they are part of the Bodo Oceanic traffic zone.                                                |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Same set as airports allocated to ISO code 'NO+SJ'.                                                                                                                                   |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Poland                 | All airports with ICAO code starting by 'EP'. Same set as airports allocated to ISO code 'PL'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Portugal               | All airports with ICAO code starting by 'LP'. Same set as airports allocated to ISO code 'PT'.                                                                                        | This is a difference with respect to the 'Lisbon FIR' STATFOR traffic zone which does not include airports in the Azores, Madeira, etc. \[include full list\] which are allocated to the 'Santa Maria FIR' traffic zone. |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Romania                | All airports with ICAO code starting by 'LR'. Same set as airports allocated to ISO code 'RO'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Serbia                 | All airports allocated to the [ISO code 'RS']{.underline} in the EUROCONTROL Airport Reference Table.                                                                                 | Note that STATFOR considers the single traffic zone 'Serbia/Montenegro'.                                                                                                                                                 |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slovakia               | All airports with ICAO code starting by 'LZ'. Same set as airports allocated to ISO code 'SK'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Slovenia               | All airports with ICAO code starting by 'LJ'. Same set as airports allocated to ISO code 'SI'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Spain                  | All airports with ICAO code starting by 'LE', 'GC' plus Ceuta (GECE) and Melilla (GEML).                                                                                              |                                                                                                                                                                                                                          |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Same set as airports allocated to ISO code 'ES'.                                                                                                                                      |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sweden                 | All airports with ICAO code starting by 'ES'. Same set as airports allocated to ISO code 'SE'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Switzerland            | All airports with ICAO code starting by 'LS' excluding airports in Liechtenstein (for the time being only LSXB).                                                                      | This is a small difference with respect to the Switzerland STATFOR traffic zone, which includes Liechtenstein as it is too small to have its own traffic zone.                                                           |
|                        |                                                                                                                                                                                       |                                                                                                                                                                                                                          |
|                        | Same set as airports allocated to ISO code 'CH'.                                                                                                                                      |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Türkiye                | All airports with ICAO code starting by 'LT'. Same set as airports allocated to ISO code 'TR'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ukraine                | All airports with ICAO code starting by 'UK'. Same set as airports allocated to ISO code 'UA'.                                                                                        |                                                                                                                                                                                                                          |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| United Kingdom         | All airports with ICAO code starting by 'EG'. Same set as airports allocated to ISO code 'GB+GG+IM+JE'.                                                                               | It does not include Gibraltar airport (LXGB) but includes the Channel Island airports - Guernsey (EGJB), Isle of Man (EGNS) and Jersey (EGJJ).                                                                           |
+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: PRU country definitions (NM area\* only)

In addition to the country definitions above, depending on the metric , in particular when presenting flights including overflights, the designations below are also used.

| Designation        | Airports included                                                                   | Additional notes                                                                               |
|--------------------|-------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| Belgium/Luxembourg | All airports included in the entries for Belgium and Luxembourg.                    | Typically used when presenting flights including overflights as NM calculates them together.   |
| Serbia/Montenegro  | All airports included in the entries for Serbia and Montenegro.                     | Typically used when presenting flights including overflights as NM calculates them together.   |
| Spain Canaries     | All airports with ICAO code starting by 'LE', plus Ceuta (GECE) and Melilla (GEML). | Typically used when presenting flights including overflights as NM calculates them separately. |
| Spain Continental  | All airports with ICAO code starting by 'GC'.                                       | Typically used when presenting flights including overflights as NM calculates them separately. |

: PRU additional traffic zone definitions

## STATFOR

See traffic zones definition in the [Regions definition document](media/eurocontrol-forecast-2020-2024-region-definition.pdf).

## NM

See the Agency's [Reporting Assumptions and Descriptions](https://www.eurocontrol.int/publication/reporting-assumptions-and-descriptions) page.
